import './reference';
import './this';
import './closures';
import './recursive-function';
import './spread-rest';
import './destructuring';
import './async';
import './generators';
import './programming-paradigms/programming-paradigms';